Statement::column_table_name
rusqlite/rusqlite pull request #1354
Opened 2023-06-25 08:39 UTC by baummarten

Wrapper around https://www.sqlite.org/capi3ref.html#sqlite3_column_database_name

2023-06-25 08:52 UTC, gwenn commented
See https://sqlite.org/c3ref/column_database_name.html
> These APIs are only available if the library was compiled with the [SQLITE_ENABLE_COLUMN_METADATA](https://sqlite.org/compile.html#enable_column_metadata) C-preprocessor symbol.

Which means that you must introduce a feature...

2023-06-25 09:00 UTC, gwenn requested changes

2023-06-25 09:00 UTC, gwenn commented on src/raw_statement.rs
> +            let ptr = ffi::sqlite3_column_table_name(self.ptr, idx);
`sqlite3_column_table_name` depends on `SQLITE_ENABLE_COLUMN_METADATA` compile option.
So you must introduce a feature.

2023-06-26 18:46 UTC, baummarten commented
Right, sorry, I didn't notice that. So it would have to depend on `bundled`, or else it would risk breaking someone's build if this feature gets enabled and the system sqlite wasn't compiled with this option. Seems more trouble than it's worth then; since writing the PR I found out I was using it wrongly to disambiguate columns after a join, where I should have been usin `as` to rename them instead. Nevermind then, sorry for the trouble.

2023-06-26 18:46 UTC, closed without merging